### ISSUE TITLE
[docs] 기획서 작성

### ISSUE THREAD

**Issue by mei-zy** [MeongFind/meong-Find#2]
- [x] : 기획의도
- [x] : 사용언어
- [x] : usecase
- [x] : 스토리보드
- [x] : 피그마 시안

**Comment by h-sick** [comment]
@urther 마이페이지에서 유저 이모티콘 필요 여부 모르겠음
- 이미지를 넣을 수 있게 하거나 아예 공간을 없애야 할지 의논 필요

**Comment by h-sick** [comment]
mock data 구조 설계

**Comment by mei-zy** [comment]
readme 파일 - figma 수정

**Comment by mei-zy** [comment]
- [x] : 상태 변경 삭제해주고
- [x] : 알람 대신 로그아웃으로 기능 대체
- [x] : 검색 기능 메인페이지에서만 가능하게끔
- [x] : 일단 소셜 삭제
- [x] : usecase 같이 수정

**Comment by ywc8851** [comment]
- [x] : 스토리보드수정 @urther
